

--
-- Volcado de datos para la tabla `tb_art`
--

INSERT INTO `tb_art` (`id`, `articulo`) VALUES
(1, 'Procesador INTEL'),
(2, 'Procesador AMD'),
(3, 'Memoria RAM PC'),
(4, 'Board para AMD'),
(5, 'Disco Duro Portatil'),
(6, 'Board para INTEL'),
(7, 'Disco Duro PC'),
(8, 'Memoria RAM Portatil'),
(9, 'Tarjeta de video'),
(10, 'Tablet'),
(11, 'Chasis (CASE)'),
(12, 'Unidad DVD'),
(13, 'Monitor'),
(14, 'Licenciamiento'),
(15, 'Disco Externo USB'),
(16, 'Impresora'),
(17, 'Proyector'),
(18, 'Sistema POS'),
(19, 'Memoria USB'),
(20, 'Memoria MICRO SD'),
(21, 'CÃ¡mara '),
(22, 'Tinta'),
(23, 'Teclado'),
(24, 'Mouse'),
(25, 'Tarjetas De TV'),
(26, 'Diadema'),
(27, 'Parlantes'),
(28, 'Otros'),
(30, 'Microfono'),
(31, 'Cables y otros'),
(32, 'Cargador'),
(33, 'Base refrigerantes portatil'),
(34, 'Tarjeta de red'),
(35, 'Router'),
(36, 'Fuente de energía'),
(37, 'UPS'),
(38, 'Computadores De Escritorio'),
(39, 'Computadores Todo En Uno'),
(40, 'Computadores Portatil');
